name: Debug macOS Runner

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Set up tmate session for SSH
        run: |
          brew install tmate
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
          tmate -S /tmp/tmate.sock display -p '#{tmate_web}'

      - name: Keep runner alive for debugging
        run: sleep 3600

